baseURL = '/'
languageCode = 'en-us'
title = 'Suryavir Kapur'
theme = "binario"

[Params.Social]
  email = "hello@suryavirkapur.com"
  twitter = "suryavirkapur"
  github = "suryavirkapur"

[Params]
  description = "thoughts, stories and ideas." 
  opengraph = true 
  schema = true
  twitter_cards = true 
  columns = 2 
  mainSections = ["posts"] 
  dateFormat = "January 02, 2006" 
  colorTheme = "dark-blue" 
  mainMenuAlignment = "left"